/* Copyright (c) 2006-2012 MIS Institute of the HEIG affiliated to the University of
** Applied Sciences of Western Switzerland. All rights reserved.
** IN NO EVENT SHALL THE MIS INSTITUTE NOR THE HEIG NOR THE UNIVERSITY OF APPLIED
** SCIENCES OF WESTERN SWITZERLAND BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL,
** INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS
** DOCUMENTATION, EVEN IF THE MIS INSTITUTE OR THE HEIG OR THE UNIVERSITY OF APPLIED
** SCIENCES OF WESTERN SWITZERLAND HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
** THE MIS INSTITUTE, THE HEIG AND THE UNIVERSITY OF APPLIED SCIENCES OF WESTERN SWIT-
** ZERLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFT-
** WARE PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE MIS INSTITUTE NOR THE HEIG
** AND NOR THE UNIVERSITY OF APPLIED SCIENCES OF WESTERN SWITZERLAND HAVE NO OBLIGATION
** TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
*/
/* File ZottaOS.h: Selects the kernel for the application.
** Version date: July 2011
** Authors: MIS-TIC
*/

#ifndef _ZOTTAOS_H_
#define _ZOTTAOS_H_

#include "ZottaOS_Config.h"     /* Import the kernel version */

#ifndef _ASM_

#include "ZottaOS_Types.h"      /* Type definitions */
#include "ZottaOS_Interrupts.h" /* Interrupt priorities and ISR index definitions */

#endif /* _ASM_ */

#if defined(ZOTTAOS_VERSION_HARD)
   #include "ZottaOSHard.h"
#elif defined(ZOTTAOS_VERSION_SOFT)
   #include "ZottaOSSoft.h"
#else
   #error ZOTTAOS_VERSION undefined!
#endif

#endif /* _ZOTTAOS_H_ */
